### ISSUE TITLE
Registry Credentials documentaion 

### ISSUE THREAD

**Issue by RinkiyaKeDad** [okteto/docs#481]
In the UI the feature is called "Registry Credentials". If someone were to see this in the UI and search for it in the docs they might not land in the right place since in the docs it's under the [privateRegistry](https://www.okteto.com/docs/1.12/self-hosted/administration/configuration/#privateregistry) heading. Either we should change the name in one of the places or maybe have a new page in docs called "Registry Credentials" with more info on how to configure them.

<img width="1295" alt="Untitled" src="https://github.com/okteto/docs/assets/56963264/8565e7b2-b79e-45c6-b4a3-8b6647501e81">

**Comment by pchico83** [comment]
@omnomagonz the goal of this feature is to deprecate `privateRegistries`, because `privateRegistries` forces you to add your credentials in plain and all Self-hosted users complain about this.
While we don't have UI to add the credentials from there, could we document how to directly create the CRD and point to those docs from "Registry Credentials"? I would also remove the `privateRegistries` references from our docs

**Comment by omnomagonz** [comment]
@pchico83 Is creating the CRD something that needs to be documented independent of the new admin feature?

And for removing `privateRegistries`, would it still exist and we just don't recommend people use it or have we removed it in this feature work?

**Comment by ifbyol** [comment]
Closing as this was already implemented
